[theme]
base="light"
primaryColor="#4A90E2"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F7F9FC"
textColor="#111111"

[client]
toolbarMode="minimal"
showSidebarNavigation=true

[server]
headless=true
enableCORS=true
enableXsrfProtection=false

[browser]
gatherUsageStats=false

[global]
disableWatchdogWarning=true
